### ISSUE TITLE
script resubmiteador

### ISSUE THREAD

**Issue by dianadrago** [CSB-IG/parallel-aracne#1]
Si al someter un cluster de jobs algunas fracasan, de todas maneras quedan regados adjs vacíos.
Es necesario un programa que examine el queue de htcondor, lo coteje con los adj vacíos, genere un archivo .condor nuevo y quizá borre los jobs del queue.

**Comment by xihh87** [comment]
Ya no debería ser un problema, si los trabajos fracasan, no se generan adjs
debido a que usamos mk [reconstruyendo atómicamente](http://cr.yp.to/redo/atomic.html ).
Si el trabajo falla, no se genera el archivo.
